### ISSUE TITLE
Definiranje i izrada baze podataka

### ISSUE THREAD

**Issue by josipfuduric** [AIR-FOI-HR/AIR1903#5]
Definirati ERA model baze podataka. Nakon što je definiran ERA model izraditi samu bazu podataka na temelju ERA modela

**Comment by aalagic** [comment]
Definiran ERA model baze podataka i implementiran u MySQL bazi podataka.

![76776578_464643284166037_6984884444238708736_n](https://user-images.githubusercontent.com/48157311/69272025-364acc80-0bd6-11ea-920e-fc3381291bdc.png)
